version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    container_name: nestjs_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3030:3030'
      - '9229:9229'
    environment:
      MONGODB_HOST: mongodb
    command: sh -c "pnpm run start:debug"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    restart: always
    depends_on:
      - mongodb

volumes:
  mongo_data:
